# Generated by Django 3.2.16 on 2023-05-27 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('section_by_time', '__first__'),
        ('disease', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseBySection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cur_section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='section_by_time.sectionbytime')),
                ('disease', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='disease.disease')),
            ],
            options={
                'db_table': 'disease_by_section',
                'managed': True,
            },
        ),
    ]
