# Generated by Django 3.2.16 on 2023-05-26 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disease', '0001_initial'),
        ('plants_section', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseBySection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('board', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plants_section.plantssection')),
                ('disease', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='disease.disease')),
            ],
            options={
                'db_table': 'disease_by_section',
                'managed': True,
            },
        ),
    ]
