# Generated by Django 3.2.16 on 2023-05-11 14:15

import datetime
from django.db import migrations, models
import django.db.models.deletion
import plants_section.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantsSection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('input_image', models.ImageField(null=True, upload_to=plants_section.models.user_directory_path_input)),
                ('status', models.CharField(default='0', max_length=1)),
                ('number', models.IntegerField(default=1)),
                ('is_delete', models.CharField(default='0', max_length=1)),
                ('farm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farm.farm')),
            ],
            options={
                'db_table': 'plants_section',
                'managed': True,
            },
        ),
    ]
