# Generated by Django 3.2.16 on 2023-05-11 14:16

from django.db import migrations, models
import django.db.models.deletion
import section_detail.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plants_section', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('leaf_image', models.FileField(null=True, upload_to=section_detail.models.user_directory_path)),
                ('status', models.CharField(default='0', max_length=1)),
                ('is_disease', models.CharField(default='0', max_length=1)),
                ('board', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plants_section.plantssection')),
            ],
            options={
                'db_table': 'section_detail',
                'managed': True,
            },
        ),
    ]
