# Generated by Django 3.2.16 on 2023-05-27 10:00

import datetime
from django.db import migrations, models
import django.db.models.deletion
import section_by_time.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plants_section', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionByTime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('image', models.ImageField(null=True, upload_to=section_by_time.models.user_directory_path)),
                ('status', models.CharField(default='0', max_length=1)),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plants_section.plantssection')),
            ],
            options={
                'db_table': 'section_by_time',
                'managed': True,
            },
        ),
    ]
